### ISSUE TITLE
Unclear how to install

### ISSUE THREAD

**Issue by sente** [kiliankoe/location#1]
I'd like to give this a shot but I need assistance compiling/installing the project.

When trying to install with Brew I get the following error:

```
stu@powderhouse ~ $ brew install location
==> Installing kiliankoe/location/location
==> Downloading https://github.com/kiliankoe/location/archive/0.2.0.tar.gz
Already downloaded: /Users/stu/Library/Caches/Homebrew/location-0.2.0.tar.gz
==> Building location
==> swift build --disable-sandbox -c release --static-swift-stdlib
Last 15 lines from /Users/stu/Library/Logs/Homebrew/location/01.swift:
    public static func ==(lhs: AnyIndex, rhs: AnyIndex) -> Bool
                       ^
Swift.Equatable:149:24: note: protocol requires function '==' with type '(PathImpl, PathImpl) -> Bool'; do you want to add a stub?
    public static func ==(lhs: Self, rhs: Self) -> Bool
                       ^
/private/tmp/location-20180419-15219-ts9nj3/location-0.2.0/.build/checkouts/swift-package-manager-7563514128626468262/Sources/Basic/Path.swift:104:14: error: expression pattern of type 'String' cannot match values of type 'String.Element?' (aka 'Optional<Character>')
        case "/":
             ^~~
/private/tmp/location-20180419-15219-ts9nj3/location-0.2.0/.build/checkouts/swift-package-manager-7563514128626468262/Sources/Basic/Path.swift:106:14: error: expression pattern of type 'String' cannot match values of type 'String.Element?' (aka 'Optional<Character>')
        case "~":
             ^~~
error: terminated(1): /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-build-tool -f /private/tmp/location-20180419-15219-ts9nj3/location-0.2.0/.build/release.yaml main
Fetching https://github.com/apple/swift-package-manager
Cloning https://github.com/apple/swift-package-manager
Resolving https://github.com/apple/swift-package-manager at master

If reporting this issue please do so to (not Homebrew/brew or Homebrew/core):
kiliankoe/location

/usr/local/Homebrew/Library/Homebrew/utils/github.rb:220:in `raise_api_error': curl failed!  (GitHub::Error)
curl: (22) The requested URL returned error: 422 Unprocessable Entity
curl: (3) <url> malformed
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:178:in `open_api'
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:292:in `search'
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:225:in `search_issues'
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:238:in `issues_for_formula'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:368:in `fetch_issues'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:364:in `issues'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:418:in `dump'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:139:in `rescue in <main>'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:31:in `<main>'
```

**Comment by kiliankoe** [comment]
Looks like it was failing whilst trying to build the swift package manager, a part of which this pulls in as a dependency. I also just saw that I was relying on the master branch of that repo 🤦‍♂️ I just updated that to pin to a specific revision and verified that it builds and runs locally. Could you run `brew update` and try again? Hopefully that works now 😊 

If it still doesn't, could you share your Xcode version just in case? 9.3 (using Swift 4.1) seems to work on my end at least.
